version 2
jobs:
   build:
     docker:
      - image diehlpk/teaching
    steps:
     - checkout
     - run:
     name: Compile
     command: find -name "*.cpp" -exec g++ "{}" -o "{}".exec ";"
    - run:
     name: Check
     command: find -name "*.cpp" -exec cppcheck --enable=warning,performance "{}" ";"
