version: 2
jobs:
  build:
    docker:
      - image: diehlpk/teaching
    steps:
      - checkout
      - run: find -name "*.cpp" -exec g++ "{}" -o "{}".exec ";"
      - run: find -name "*.cpp" -exec cppcheck --enable=warning,performance "{}" ";"
      - run: find -maxdepth 1 -name "exercise*.tex" -exec latexmk -pdflatex="pdflatex" -pdf "{}" ";"
      - run: mkdir final && cp exercise*.pdf final  
      - store_artifacts:
          path: final
          destination: exercises
