From fedora:31
MAINTAINER Patrick Diehl <patrickdiehl@lsu.edu>

RUN dnf update -y
RUN dnf install hpx-devel cmake git gcc-c++ cppcheck texlive-scheme-medium latexmk texlive-doclicense pandoc gnuplot texlive-beamerswitch -y 
